import base64
import re
import io
import PIL.Image as Image
from array import array

y = b'/9j/4T0nRXhpZgAATU0AKgAAAAgACwEQAAIAAAARAAAAkgExAAIAAAA9AAAAowESAAMAAAABAAYAAAEyAAIAAAAUAAAA4AITAAMAAAABAAEAAIdpAAQAAAABAAABCwEoAAMAAAABAAIAAIglAAQAAAABAAADHgEaAAUAAAABAAAA9AEbAAUAAAABAAAA/AEPAAIAAAAHAAABBAAAA/tSZWRtaSBOb3RlIDUgUHJvAHdoeXJlZC11c2VyIDkgUEtRMS4xODA5MDQuMDAxIFYxMS4wLjUuMC5QRUlNSVhNIHJlbGVhc2Uta2V5cwAyMDIxOjA3OjE2IDAwOjA0OjA4AAAAAEgAAAABAAAASAAAAAFYaWFvbWkAAB2IJwADAAAAARkAAACIIgADAAAAAQAAAACCnQAFAAAAAQAAAm2CmgAFAAAAAQAAAnWZmQACAAAAJgAAAn2iFwADAAAAAQACAACSkgACAAAABwAAAqOSkQACAAAABwAAAqqSkAACAAAABwAAArGSCgAFAAAAAQAAAriSCQADAAAAAQAQAACSBwADAAAAAQACAACkBgADAAAAAQAAAACgBQAEAAAAAQAAAwCkBQADAAAAAQAEAACQBAACAAAAFAAAAsCgAwAEAAAAAQAAC7ikAwADAAAAAQAAAACQAwACAAAAFAAAAtSSAwAKAAAAAQAAAuigAgAEAAAAAQAAD6CkAgADAAAAAQAAAACSAgAFAAAAAQAAAvCRAQAHAAAABAECAwCgAQADAAAAAQABAACjAQAHAAAAAQEAAACSAQAKAAAAAQAAAviQAAAHAAAABDAyMjCgAAAHAAAABDAxMDAAAAAAAAAA3AAAAGQAAAABAAAADnsic2Vuc29yX3R5cGUiOiJyZWFyIiwibWlycm9yIjpmYWxzZX0AODE3MTQ1ADgxNzE0NQA4MTcxNDUAAAAO4gAAA+gyMDIxOjA3OjE2IDAwOjA0OjA4ADIwMjE6MDc6MTYgMDA6MDQ6MDgA///+GQAAAGQAAAD'


#with open("imageToSave.png", "wb") as fh:
#    fh.write(decode_base64(y))

def decode_base64(data, altchars=b'+/'):
    """Decode base64, padding being optional.

    :param data: Base64 data as an ASCII byte string
    :returns: The decoded byte string.

    """
    data = re.sub(rb'[^a-zA-Z0-9%s]+' % altchars, b'', data)  # normalize
    missing_padding = len(data) % 4
    if missing_padding:
        data += b'='* (4 - missing_padding)
    return base64.b64decode(data, altchars)

img = Image.frombytes('L', (200,200), decode_base64(y))
img.save('imageToSave.png')

print(decode_base64(y))
